name = input("What is your name?")
age = input("How old are you?")
target_year = input("In which year you want to go korea")

age = int(age)
target_year = int(target_year)
future_age = age + (target_year -  2026)
print("------Mission korea age calculator---")
print("Name: ",name)
print("Current age: ", age)
print("Target age: " ,target_year)
print("Future age : ", future_age)
